[project]
name = "multi-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Davinder Singh", email = "davindersingh46997@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
multi-agent = "multi_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
